version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=password

    command: npm start

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
