version: "3"
services:
  node-app: # name of the container
    build: . # location of the Dockerfile
    ports:
      - "3000:3000" #host:container ports
    environment:
      - PORT=3000
    depends_on: 
      - mongo # starts the mongo container before the node container
    # env_file:
    #   - ./.env
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db # named volume, persists the data even if the container is removed

volumes:
  mongo-db:  #required for named volumes
